### PR TITLE
bno080x_heading_example

### PR DESCRIPTION
**Pull request by yugyesh**
Using rotation vectors to find the heading value

### CODE REVIEW

**Comment by yugyesh** [comment]
Calculating yaw and heading value from the rotation vector

**Comment by ladyada** [comment]
nice! can you run `black` on your example? that will format it nicely
@kattni can help you if you dont know how

**Comment by kattni** [comment]
@yugyesh Do you need assistance running Black on your code? We can't merge it until CI passes, and there are two issues making it fail - one is that you need to run black to format it properly, and two, you need to add licensing info at the top of the file. Please let me know if this is something you're interested in doing. I can assist you over the next couple of days if needed.

**Comment by yugyesh** [comment]
Dear Kattni,
I hope this email finds you well in your good health
This is my first time contributing to open source. I will be grateful for
your assistance in running black on the source code. I am not familiar on
with black. In addition, could you please elaborate what licensing I must
add in the source code. I will be happy to have your quick response.
Thank you


Best regards
KC YUGESH
Software engineer, Intelligence Design, South korea

**Comment by kattni** [comment]
Hello @yugyesh! Thank you for your submission, I really appreciate it. 

I have a Learn guide that explains how to run Black. Please start by reading this: https://learn.adafruit.com/improve-your-code-with-pylint/black

If you have any questions after reading the guide, please post them here.

For licensing, you need to add the following to the top of the file:
```
# SPDX-FileCopyrightText: 2021 KC YUGESH
# SPDX-License-Identifier: Unlicense
```
You can change `Unlicense` to a license of your choice, such as `MIT` if you wish. Or you can leave it as `Unlicense`.

**Comment by yugyesh** [comment]
Hello @kattni  yes I have used the github interface to in order to initiate the pull request. However the suggested changes has been performed using git bash.

Even after formatting using black the check is getting failed 

image

**Review by kattni — APPROVED** [review]
@yugyesh Thank you! You did everything perfectly! I'm going to merge this.

This failure is unrelated to what you contributed. Your contribution is passing.

**Pull request merged**
